<?php
if (function_exists('acf_add_local_field_group')) :

    acf_add_local_field_group(array(
        'key' => 'group_62b9a38e8ab19',
        'title' => 'Banner',
        'fields' => array(
            array(
                'key' => 'field_62b9a3949e4b4',
                'label' => 'Link',
                'name' => 'link',
                'type' => 'url',
                'instructions' => 'Informe um link que você deseja que o banner leve o usuário caso ele clique sobre ele. (Opcional)',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_62b9a4239e4b5',
                'label' => 'Selecione onde você quer que esse banner apareça:',
                'name' => 'local_banner',
                'type' => 'select',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    1 => 'Inicio',
                    2 => 'Inicio Publicidade 1',
                    3 => 'Inicio Publicidade 2',
                    4 => 'Quem Somos 1',
                    5 => 'Quem Somos 2',
                    6 => 'Publicidade Campanha',
                ),
                'default_value' => false,
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'label',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_62b9a4d19e4b6',
                'label' => 'Banner',
                'name' => 'banner',
                'type' => 'image',
                'instructions' => 'Tamanho de Imagem Recomendada 300x300 pixels, caso seja publicidade é recomendado uma imagem de 1200x190 pixels',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'banner',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

endif;